### ISSUE TITLE
Display issue with pagination being cut off in Safari browser

### ISSUE THREAD

**Issue by sebastianlyserena** [nodes-frontend/nodes-ui#18]
## Issue

When user views several of pages in our backends in the Safari browser version 10, the pagination is cut off at the bottom of page. Pagination seems to be outside viewport, so that the user cannot scroll to it. This is not an issue in chrome or firefox

![screen shot 2017-03-14 at 11 48 31](https://cloud.githubusercontent.com/assets/8152466/23897111/2a7a168e-08ac-11e7-98e7-a00cca6edbe4.png)

---

## Uncommenting the following height property seems to fix it in safari 

https://github.com/nodes-frontend/nodes-ui/blob/master/scss/core/_core-layout.scss#L150

```css
.core-layout__content {
  /* height: 100%; */
  max-height: 100%;
  overflow: auto;
  -webkit-overflow-scrolling: touch;
  width: 100%;
}
```

![screen shot 2017-03-14 at 11 49 21](https://cloud.githubusercontent.com/assets/8152466/23897164/53ea82ce-08ac-11e7-87f0-91b81adb2099.png)
